version: "3.8"

services:
  xray:
    image: teddysun/xray
    container_name: xray-reality
    restart: always
    ports:
      - "2087:443"
    volumes:
      - ./config.json:/etc/xray/config.json:ro